#%RAML 1.0 DataType

type: object
properties:
      itemId:
        description: unique Id corresponds to Item
        example: 1
        type: number
        format: int
      itemName:
        description: Name for the Item
        example: abc
        type: string
      itemCost:
        description: Cost for each unit
        example: 100
        type: number
        format: double